### ISSUE TITLE
Замечания 1

### ISSUE THREAD

**Issue by arri1** [team-dev-spring-2022/teamASDA#5]
1. Написать readme что за проект, как билдить, как запускать проект
2. лейблы проставить
3. пулл реквест сделать более информативным
4. не забываем апрувить код
5. много строчек кода

**Comment by SomeoneUnknownPerson** [comment]
2. Лейблы проставлены
3. Пулл реквесты более информативны
4. Апрув кода есть
5. Коммиты теперь до 25 строк

**Comment by aKmiron** [comment]
1. raedme обновлен
