### ISSUE TITLE
Необходимо переименовать HomeScreen в ToDoScreen

### ISSUE THREAD

**Issue by aKmiron** [team-dev-spring-2022/teamASDA#85]
Необходимо переименовать HomeScreen в ToDoScreen

_Originally posted by @aKmiron in https://github.com/team-dev-spring-2022/teamASDA/pull/84#pullrequestreview-885461233_

**Comment by SemyonShamaev** [comment]
Иссью не был выполнен, так как файл HomeScreen был удален
